routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{slug}', 'PageController@show')->name('page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	// Route::get('pages', 'PageController@index')->name('pages.index');

	// Route::get('pages/{id}', 'PageController@show')->name('pages.show');

	Route::resource('pages', 'PageController');
	Route::resource('services', 'ServiceController');
	Route::resource('menu', 'MenuController');
	Route::get('parameters', 'ParametersController@show')->name('parameters.show');
	Route::get('parameters/edit', 'ParametersController@edit')->name('parameters.edit');
	Route::put('parameters', 'ParametersController@update')->name('parameters.update');
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
});

resources/views/admin/page/create.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('pages.index') }}">Pages</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection

@section('title')
Create Page
@endsection

@section('content')
{!! Form::open(['url' => route('pages.store'), 'method' => 'post', 'files' => true]) !!}
    @include('admin.page.form')
{!! Form::close() !!}
<div><a href="{{ route('pages.index') }}">List</a></div>
@endsection

resources/views/admin/page/edit.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('pages.index') }}">Pages</a></li>
    <li class="breadcrumb-item"><a href="{{ route('pages.show', ['id' => $page->id]) }}">{{ $page->name }}</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection

@section('title')
Edit {{ $page->name }}
@endsection

@section('content')
{!! Form::open(['url' => route('pages.update', ['id' => $page->id]), 'method' => 'put', 'files' => true]) !!}
    @include('admin.page.form', ['page' => $page])
{!! Form::close() !!}
<div><a href="{{ route('pages.index') }}">List</a></div>
<div><a href="{{ route('pages.show', ['id' => $page->id]) }}">show</a></div>
@endsection

resources/views/admin/page/form.blade.php
<div class="card card-default">
  <form role="form">
    <div class="card-body">
      <div class="form-group">
        {{ Form::label('slug', 'Slug') }}
        {{ Form::text('slug', isset($page) ? $page->slug : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
		{{ Form::label('name', 'Name') }}
        {{ Form::text('name', isset($page) ? $page->name : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', isset($page) ? $page->title : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('description', 'Description') }}
        {{ Form::textarea('description', isset($page) ? $page->description : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('keywords', 'Keywords') }}
        {{ Form::textarea('keywords', isset($page) ? $page->keywords : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('content', 'Content') }}
        {{ Form::textarea('content', isset($page) ? $page->content : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('image', 'Image') }}
        {{ Form::file('image', ['class' => 'form-control']) }}
      </div>
    </div>
    <div class="card-footer">
    	{{ Form::button('<i class="fas fa-check"></i> Send', ['type' => 'submit', 'class' => 'btn btn-primary']) }}
    </div>
  </form>
</div>

resources/views/admin/page/index.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item active">Pages</li>
@endsection

@section('title')
Pages
@endsection

@section('content')
<div class="card">
  <div class="card-body p-0">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th style="width: 10px">#</th>
          <th>Name</th>
          <th>Operations</th>
        </tr>
      </thead>
      <tbody>
		@foreach($pages as $page)
        <tr>
          <td>{{ $page->id }}</td>
          <td><a href="{{ route('pages.show', ['id' => $page->id]) }}">{{ $page->name }}</a></td>
          <td></td>
        </tr>
		@endforeach	
      </tbody>
    </table>
  </div>
  <!-- /.card-body -->
</div>
<div><a href="{{ route('pages.create') }}">Create</a></div>
@endsection

resources/views/admin/page/show.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('pages.index') }}">Pages</a></li>
    <li class="breadcrumb-item active">{{ $page->name }}</li>
@endsection

@section('title')
{{ $page->name }}
@endsection

@section('content')
<div class="card">
  <div class="card-body p-0">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Slug</td>
          <td>{{ $page->slug }}</td>
        </tr>
        <tr>
          <td>Name</td>
          <td>{{ $page->name }}</td>
        </tr>
        <tr>
          <td>Title</td>
          <td>{{ $page->title }}</td>
        </tr>
        <tr>
          <td>Description</td>
          <td>{{ $page->description }}</td>
        </tr>
        <tr>
          <td>Keywords</td>
          <td>{{ $page->keywords }}</td>
        </tr>
        <tr>
          <td>Content</td>
          <td>{{ $page->content }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- /.card-body -->
</div>

<div><a href="{{ route('pages.index') }}">List</a></div>
<div><a href="{{ route('pages.edit', ['id' => $page->id]) }}">edit</a></div>
<div>{!! Form::open(['url' => route('pages.destroy', ['id' => $page->id]), 'method' => 'delete']) !!}
	{{ Form::button('<i class="fas fa-times"></i> Delete', ['type' => 'submit']) }}
{!! Form::close() !!}</div>
@endsection