routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{slug}', 'PageController@show')->name('page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	// Route::get('pages', 'PageController@index')->name('pages.index');

	// Route::get('pages/{id}', 'PageController@show')->name('pages.show');

	Route::resource('pages', 'PageController');
	Route::resource('services', 'ServiceController');
	Route::resource('menu', 'MenuController');
	Route::get('parameters', 'ParametersController@show')->name('parameters.show');
	Route::get('parameters/edit', 'ParametersController@edit')->name('parameters.edit');
	Route::put('parameters', 'ParametersController@update')->name('parameters.update');
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = ['image', 'name', 'title', 'description', 'keywords', 'content'];

    public function images()
    {
        return $this->hasMany('App\ServiceImage');
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ServiceRequest;
use App\Http\Controllers\Controller;
use App\Traits\UploadImageTrait;
use App\Service;

class ServiceController extends Controller
{
    use UploadImageTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Service::paginate(20);
        return view('admin.service.index', ['services' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.service.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ServiceRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServiceRequest $request)
    {
        $service = new Service();
        $service->fill($request->all());
        if ($file = $request->file('image')) {
            $image = $this->saveImage($file, 'services');
            $service->image = $image;
        }
        $service->save();
        return redirect()->route('services.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Service::where('id', $id)->firstOrFail();
        return view('admin.service.show', ['service' => $data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Service::where('id', $id)->firstOrFail();
        return view('admin.service.edit', ['service' => $data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ServiceRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ServiceRequest $request, $id)
    {
        $service = Service::where('id', $id)->firstOrFail();
        $service->fill($request->all());
        if ($file = $request->file('image')) {
            $image = $this->saveImage($file, 'services');
            $service->image = $image;
        }
        $service->save();
        return redirect()->route('services.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Service::where('id', $id)->firstOrFail();
        $service->delete();
        return redirect()->route('services.index');
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Service;

class ServiceController extends Controller
{
	public function FunctionName($value='')
	{
    	$data = Service::where('slug', $slug)->firstOrFail();
    	return view('service', ['service' => $data]);
	}
}

resources/views/admin/service/create.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('services.index') }}">Services</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection

@section('title')
Create Service
@endsection

@section('content')
{!! Form::open(['url' => route('services.store'), 'method' => 'post', 'files' => true]) !!}
    @include('admin.service.form')
{!! Form::close() !!}
<div><a href="{{ route('services.index') }}">List</a></div>
@endsection

resources/views/admin/service/edit.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('services.index') }}">Services</a></li>
    <li class="breadcrumb-item"><a href="{{ route('services.show', ['id' => $service->id]) }}">{{ $service->name }}</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection

@section('title')
Edit {{ $service->name }}
@endsection

@section('content')
{!! Form::open(['url' => route('services.update', ['id' => $service->id]), 'method' => 'put', 'files' => true]) !!}
    @include('admin.service.form', ['service' => $service])
{!! Form::close() !!}
<div><a href="{{ route('services.index') }}">List</a></div>
<div><a href="{{ route('services.show', ['id' => $service->id]) }}">show</a></div>
@endsection

resources/views/admin/service/form.blade.php
<div class="card card-default">
  <form role="form">
    <div class="card-body">
      <div class="form-group">
		{{ Form::label('name', 'Name') }}
        {{ Form::text('name', isset($service) ? $service->name : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', isset($service) ? $service->title : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('description', 'Description') }}
        {{ Form::textarea('description', isset($service) ? $service->description : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('keywords', 'Keywords') }}
        {{ Form::textarea('keywords', isset($service) ? $service->keywords : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('content', 'Content') }}
        {{ Form::textarea('content', isset($service) ? $service->content : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('image', 'Image') }}
        {{ Form::file('image', ['class' => 'form-control']) }}
      </div>
    </div>
    <div class="card-footer">
    	{{ Form::button('<i class="fas fa-check"></i> Send', ['type' => 'submit', 'class' => 'btn btn-primary']) }}
    </div>
  </form>
</div>

resources/views/admin/service/index.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item active">Services</li>
@endsection

@section('title')
Services
@endsection

@section('content')
<ul>
	@foreach($services as $service)
	<li>
		<a href="{{ route('services.show', ['id' => $service->id]) }}">{{ $service->name }}</a>
	</li>
	@endforeach	
</ul>
{{ $services->links() }}
<div><a href="{{ route('services.create') }}">Create</a></div>
@endsection

resources/views/admin/service/show.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('services.index') }}">Services</a></li>
    <li class="breadcrumb-item active">{{ $service->name }}</li>
@endsection

@section('title')
{{ $service->name }}
@endsection

@section('content')
<table>
	<tr>
		<th>Image</th>
		<td><img src="{{ asset($service->image) }}" alt="{{ $service->name }}"></td>
	</tr>
	<tr>
		<th>Slug</th>
		<td>{{ $service->slug }}</td>
	</tr>
	<tr>
		<th>Name</th>
		<td>{{ $service->name }}</td>
	</tr>
	<tr>
		<th>Title</th>
		<td>{{ $service->title }}</td>
	</tr>
	<tr>
		<th>Description</th>
		<td>{{ $service->description }}</td>
	</tr>
	<tr>
		<th>Keywords</th>
		<td>{{ $service->keywords }}</td>
	</tr>
	<tr>
		<th>Content</th>
		<td>{{ $service->content }}</td>
	</tr>
</table>
<div><a href="{{ route('services.index') }}">List</a></div>
<div><a href="{{ route('services.edit', ['id' => $service->id]) }}">edit</a></div>
<div>{!! Form::open(['url' => route('services.destroy', ['id' => $service->id]), 'method' => 'delete']) !!}
	{{ Form::button('<i class="fas fa-times"></i> Delete', ['type' => 'submit']) }}
{!! Form::close() !!}</div>
@endsection