routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{slug}', 'PageController@show')->name('page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	// Route::get('pages', 'PageController@index')->name('pages.index');

	// Route::get('pages/{id}', 'PageController@show')->name('pages.show');

	Route::resource('pages', 'PageController');
	Route::resource('services', 'ServiceController');
	Route::resource('menu', 'MenuController');
	Route::get('parameters', 'ParametersController@show')->name('parameters.show');
	Route::get('parameters/edit', 'ParametersController@edit')->name('parameters.edit');
	Route::put('parameters', 'ParametersController@update')->name('parameters.update');
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
});

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $table = 'menu';
    protected $fillable = ['name', 'href'];
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\MenuRequest;
use App\Http\Controllers\Controller;
use App\Menu;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Menu::all();
        return view('admin.menu.index', ['menu' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.menu.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\MenuRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MenuRequest $request)
    {
        $menu = new Menu();
        $menu->fill($request->all());
        $menu->save();
        return redirect()->route('menu.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Menu::where('id', $id)->firstOrFail();
        return view('admin.menu.show', ['menu' => $data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Menu::where('id', $id)->firstOrFail();
        return view('admin.menu.edit', ['menu' => $data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\MenuRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(MenuRequest $request, $id)
    {
        $menu = Menu::where('id', $id)->firstOrFail();
        $menu->fill($request->all());
        $menu->save();
        return redirect()->route('menu.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $menu = Menu::where('id', $id)->firstOrFail();
        $menu->delete();
        return redirect()->route('menu.index');
    }
}

resources/views/admin/menu/create.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('menu.index') }}">Menu</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection

@section('title')
Create Menu
@endsection

@section('content')
{!! Form::open(['url' => route('menu.store'), 'method' => 'post']) !!}
    @include('admin.menu.form')
{!! Form::close() !!}
<div><a href="{{ route('menu.index') }}">List</a></div>
@endsection

resources/views/admin/menu/edit.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('menu.index') }}">Menu</a></li>
    <li class="breadcrumb-item"><a href="{{ route('menu.show', ['id' => $menu->id]) }}">{{ $menu->name }}</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection

@section('title')
Edit {{ $menu->name }}
@endsection

@section('content')
{!! Form::open(['url' => route('menu.update', ['id' => $menu->id]), 'method' => 'put']) !!}
    @include('admin.menu.form', ['menu' => $menu])
{!! Form::close() !!}
<div><a href="{{ route('menu.index') }}">List</a></div>
<div><a href="{{ route('menu.show', ['id' => $menu->id]) }}">show</a></div>
@endsection

resources/views/admin/menu/form.blade.php
<div class="card card-default">
  <form role="form">
    <div class="card-body">
      <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', isset($menu) ? $menu->name : '', ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
		{{ Form::label('href', 'Href') }}
        {{ Form::text('href', isset($menu) ? $menu->href : '', ['class' => 'form-control']) }}
      </div>
    </div>
    <div class="card-footer">
    	{{ Form::button('<i class="fas fa-check"></i> Send', ['type' => 'submit', 'class' => 'btn btn-primary']) }}
    </div>
  </form>
</div>

resources/views/admin/menu/index.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item active">Menu</li>
@endsection

@section('title')
Menu
@endsection

@section('content')
<ul>
	@foreach($menu as $menuItem)
	<li>
		<a href="{{ route('menu.show', ['id' => $menuItem->id]) }}">{{ $menuItem->name }}</a>
	</li>
	@endforeach	
</ul>
<div><a href="{{ route('menu.create') }}">Create</a></div>
@endsection

resources/views/admin/menu/show.blade.php
@extends('admin.layout')

@section('breadcrumbs')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('menu.index') }}">Menu</a></li>
    <li class="breadcrumb-item active">{{ $menu->name }}</li>
@endsection

@section('title')
{{ $menu->name }}
@endsection

@section('content')
<table>
	<tr>
		<th>Name</th>
		<td>{{ $menu->name }}</td>
	</tr>
	<tr>
		<th>Href</th>
		<td>{{ $menu->href }}</td>
	</tr>
</table>
<div><a href="{{ route('menu.index') }}">List</a></div>
<div><a href="{{ route('menu.edit', ['id' => $menu->id]) }}">edit</a></div>
<div>{!! Form::open(['url' => route('menu.destroy', ['id' => $menu->id]), 'method' => 'delete']) !!}
	{{ Form::button('<i class="fas fa-times"></i> Delete', ['type' => 'submit']) }}
{!! Form::close() !!}</div>
@endsection